### ISSUE TITLE
[Help] Viewing the Sample `DbgPrintEx` output

### ISSUE THREAD

**Issue by AlmightyLks** [ZeroLP/WDK.Net#1]
Mind, I am a newbie to driver development, so bare with me 😄  

How would you view the SampleDriver's `DbgPrintEx` ouput?  
From my understanding you'd use the `DebugView` tool for it, but isn't the SampleDriver's output ran at startup...? 😅  
It would seem that I wouldnt be able to view that, as `DebugView` isnt listening at that moment...?

**Comment by ZeroLP** [comment]
You would need to capture kernel and capture kernel verbose output from DebugView, and then load the driver.

**Comment by AlmightyLks** [comment]
If you mind me asking
How do you explicitly reload drivers, if they aren't part of the device manager listing?

**Comment by ZeroLP** [comment]
I use kdmapper which does it on the fly.
